# fly.toml app configuration file generated for live-calendar on 2024-03-25T07:45:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'live-calendar'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/opt/app/bin/migrate'

[env]
  PHX_SERVER = 'true'
  PHX_HOST = 'live-calendar.fly.dev'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
